global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'windows'
    static_configs:
      - targets: ['change_me:9182']

  - job_name: 'mssql_exporter'
    static_configs:
      - targets: ['mssql-exporter:4000']



      